[package]
name = "ax-percpu"
description = "Define and access per-CPU data structures"
version = "0.4.17"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>", "hky1999 <976929993@qq.com>", "Su Mingxian <aarkegz@gmail.com>", "yufeng <321353225@qq.com>"]
keywords = ["arceos", "percpu"]
categories = ["development-tools::procedural-macro-helpers", "no-std"]
license = "Apache-2.0"

[features]
# Allocate process-lifetime dynamic CPU areas for host-side tests.
host-test = ["cpu-local/host-test"]

[dependencies]
cpu-local.workspace = true
ax-percpu-macros = { workspace = true }
ax-lazyinit.workspace = true
thiserror.workspace = true

[dev-dependencies]
