[package]
name = "loongarch_vcpu"
version = "0.5.15"
edition.workspace = true
authors = ["RCore Team <yuchen@tsinghua.edu.cn>"]
description = "OS-neutral LoongArch vCPU core"
repository = "https://github.com/rcore-os/tgoskits"
categories = ["embedded", "no-std"]
keywords = ["hypervisor", "loongarch", "vcpu"]
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["loongarch64-unknown-none-softfloat"]

[dependencies]
cpu-local.workspace = true
log = "0.4"
bitflags.workspace = true
tock-registers.workspace = true
