[package]
name = "ax-ipi"
version = "0.5.30"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors = ["Keyang Hu <keyang.hu@qq.com>"]
description = "ArceOS IPI management module"
license.workspace = true

[features]
default = []
host-test = ["ax-hal/host-test", "ax-sync/host-test", "ax-percpu/host-test"]

[dependencies]
ax-hal = { workspace = true, features = ["ipi"] }
ax-sync.workspace = true
ax-lazyinit.workspace = true
log.workspace = true
ax-percpu.workspace = true
